on: [push]

jobs:
  clippy:
    runs-on: ubuntu-latest
    name: Run clippy
    steps:
      - name: Clippy action step
        id: clippy
        uses: actions/docker@v2
      - name: Get clippy result
        run: cargo clippy --all-targets --all-features -- -D warnings
  test:
    runs-on: ubuntu-latest
    name: Run test
    steps:
      - name: Test action step
        id: test
        uses: actions/docker@v2
      - name: Get test result
        run: cargo make test
