on: [push]

jobs:
  clippy:
    runs-on: ubuntu-latest
    name: Run clippy
    steps:
      - name: clippy checkout
        uses: actions/checkout@v1
      - name: Clippy action step
        id: clippy
        uses: dtolnay/rust-toolchain@stable
      - name: Get clippy result
        run: cargo clippy --all-targets --all-features -- -D warnings
  test:
    runs-on: ubuntu-latest
    name: Run test
    steps:
      - name: test checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Test action step
        id: test
        uses: dtolnay/rust-toolchain@stable
      - name: Get test result
        run: cargo test --all -- --nocapture
